apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: hello
  description: A collection of all Backstage example APIs
spec:
  targets:
    - ./apis/NoGaeBook.yaml
    - ./apis/petstore-api.yaml
    - ./apis/spotify-api.yaml
    - ./apis/streetlights-api.yaml
    - ./apis/swapi-graphql.yaml
    - ./apis/wayback-archive-api.yaml
    - ./apis/wayback-search-api.yaml
